spring:
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: true # we use Webpack dev server + BrowserSync for livereload
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/hibernate
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 120000       #maximum number of milliseconds that a client will wait for a connection
      minimum-idle: 1                 #minimum number of idle connections maintained by HikariCP in a connection pool
      maximum-pool-size: 20            #maximum pool size
      idle-timeout: 10000             #maximum idle time for connection
      max-lifetime: 60000              # maximum lifetime in milliseconds of a connection in the pool after it is closed.
      pool-name: Hikari
      data-source-properties:
        v$session.program=Hikari
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
casbin:
  enableCasbin: true
  useSyncedEnforcer: false
  autoSave: true
  storeType: jdbc
  initializeSchema: create
  model: classpath:casbin/model.conf
  useDefaultModelIfModelNotSetting: true
  enableWatcher: false
logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      type:
        descriptor:
          sql:
            BasicBinder: TRACE
